language: python
before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.6
install:
  - pip install tox
  - sudo apt-get install python-enchant
script:
  - tox
env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=pep8
  - TOXENV=pycomments
